#include "A.h"




void A::perimatre()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88--67-1--7e958afb:16dee8a8159:-8000:00000000000008F8 begin
{
}
// section -64--88--67-1--7e958afb:16dee8a8159:-8000:00000000000008F8 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void A::aise()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88--67-1--7e958afb:16dee8a8159:-8000:0000000000000900 begin
{
}
// section -64--88--67-1--7e958afb:16dee8a8159:-8000:0000000000000900 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
